spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: demouser
    password: thepassword
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

axon:
  axonserver:
    servers: localhost:8124
